version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=-03
      - TZ=America/Argentina/Buenos_Aires
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      # --- CAMBIO CLAVE ---
      # En lugar de un volumen con nombre, usamos un "bind mount".
      # './n8n_data' significa: "mapea una carpeta llamada 'n8n_data' que está
      # en el MISMO directorio que este archivo docker-compose.yml".
      - ./n8n_data:/home/node/.n8n
